FROM golang:1.25-alpine AS builder

# Çalışma dizinini ayarla
WORKDIR /app

# Önce bağımlılık dosyalarını alıyoruz
COPY go.mod go.sum ./
ENV GOPROXY=https://proxy.golang.org,direct
RUN go mod download

# ŞİMDİ tüm kodu kopyalıyoruz (Go'nun dosyaları görebilmesi için burası kritik!)
COPY . .

# Kod kopyalandıktan sonra dosyaları bulutta eşitliyoruz
RUN go mod tidy

# Projeyi derliyoruz
RUN go build -o main .

# 2. Aşama: Çalıştırılabilir dosyayı küçük sisteme taşıyoruz
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 5000
CMD ["./main"]
