# 1. Aşama: Uygulamayı derliyoruz
FROM golang:1.26-alpine AS builder

# Çalışma dizinini ayarla
WORKDIR /app

# Bağımlılıkları kopyala ve indir
COPY go.mod go.sum ./
ENV GOPROXY=https://proxy.golang.org,direct
RUN go mod download

# Tüm kodu kopyala ve derle
COPY . .
RUN go build -o main .

# 2. Aşama: Sadece ihtiyacımız olan dosyaları küçük bir sisteme taşıyoruz
FROM alpine:latest
WORKDIR /root/

# Derlenen dosyayı ve varsa .env dosyasını kopyala
COPY --from=builder /app/main .

# Backend 5000 portunda çalıştığı için burayı dışarı açıyoruz
EXPOSE 5000

# Uygulamayı başlat
CMD ["./main"]